# OKTO Industrial Gold Theme Configuration
# Auto-generated by Trae Agent
# Color Palette: BNB Chain / Aster
# Identity: Cyber Yellow

class ThemeConfig:
    # Primary Palette
    PRIMARY = "#F3BA2F"  # BNB Yellow
    BACKGROUND = "#0B0E11"  # Binance Dark Deep
    ACCENT = "#21262C"  # Aster Dark Secondary
    TEXT_MAIN = "#EAECEF"  # Off-white
    
    # Terminal ANSI Codes
    RESET = "\033[0m"
    BOLD = "\033[1m"
    
    # Colors
    YELLOW = "\033[33m"  # Standard Yellow
    GOLD = "\033[38;5;220m"  # Industrial Gold (Approx)
    CYBER_YELLOW = "\033[38;2;243;186;47m"  # TrueColor #F3BA2F
    DARK_BG = "\033[48;2;11;14;17m" # Background #0B0E11
    
    # Log Levels
    INFO = f"{CYBER_YELLOW}ℹ INFO{RESET}"
    WARN = f"{GOLD}⚠ WARN{RESET}"
    ERROR = "\033[31m✖ ERROR\033[0m"
    SUCCESS = f"{CYBER_YELLOW}✔ SUCCESS{RESET}"
    
    # Branding
    LOGO_ICON = "🔱" # Trident/Fork for Liquidity/BNB
    COIN_ICON = "🪙"
    
    @staticmethod
    def header():
        return f"""
{ThemeConfig.CYBER_YELLOW}
   ____  __ __ _____  ____ 
  / __ \/ //_//_  _/ / __ \\
 / /_/ / ,<    / /  / /_/ /
 \____/_/|_|  /_/   \____/ 
{ThemeConfig.RESET}
{ThemeConfig.GOLD}:: OKTO HEADLESS NODE :: v1.1 STABLE :: BNB CHAIN ::{ThemeConfig.RESET}
"""

    @staticmethod
    def format_log(message: str, level: str = "INFO"):
        prefix = getattr(ThemeConfig, level.upper(), ThemeConfig.INFO)
        return f"{prefix} {message}"

# Usage Example:
# print(ThemeConfig.header())
# print(ThemeConfig.format_log("Liquidity Pool Detected: ASTER/USDT", "SUCCESS"))
